using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class sites_table : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Sites",
                columns: table => new
                {
                    SiteID = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    SITE_NUM = table.Column<long>(type: "bigint", nullable: false),
                    SITE_NAM = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    WHEN = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ADDR1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ADDR2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ADDR3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    GRADE_LVLS = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PHONE = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PHONE_TYPE = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TIME_AVAIL = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ROOM_NO = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    START_TIME = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    STOP_TIME = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    START_DATE = table.Column<DateTime>(type: "datetime2", nullable: true),
                    FULL = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    MIN = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    DAILY = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    AMPM = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    PERMIT = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ISSUED = table.Column<DateTime>(type: "datetime2", nullable: true),
                    STARTED = table.Column<DateTime>(type: "datetime2", nullable: true),
                    CLOSED = table.Column<DateTime>(type: "datetime2", nullable: true),
                    EXPIRES = table.Column<DateTime>(type: "datetime2", nullable: true),
                    NOTES = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    AUTORENEW = table.Column<bool>(type: "bit", nullable: false),
                    ORIGCONTRC = table.Column<DateTime>(type: "datetime2", nullable: true),
                    DIST_FEE = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    DSS_REP = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    DSS_FON = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CAPACTIY = table.Column<int>(type: "int", nullable: true),
                    SITECAP = table.Column<int>(type: "int", nullable: true),
                    CLASS = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    COUNTY = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PRINCIPAL = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SCHFONE = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CLOSINGS = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    EMERGENCY = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PADR1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PADR2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PADR3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PPHONE = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FADR1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FADR2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FADR3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FPHONE = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    EADR1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    EADR2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    EADR3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    EPHONE = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    VISIT_ID = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    WL_DATE = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    WL_COUNT = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    PC_DATE = table.Column<DateTime>(type: "datetime2", nullable: true),
                    PC_AMT = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TRANSPORT = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TPPHONE = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TEL_VOL = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    DT_VOL = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SECURITY = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SECPHONE = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SAFEPLACE = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    LOCKDOWN = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    RELOCROOM1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    RELOCROOM2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    LNDLNLOC = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ADDLOC = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ATTNOTE = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SRCSCHLS = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    RSPNSBL = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TWONAMES = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    HCPSENT = table.Column<DateTime>(type: "datetime2", nullable: true),
                    HCPAPPR = table.Column<DateTime>(type: "datetime2", nullable: true),
                    ENROLLMENT = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    COEXP = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    WAIVEREXP = table.Column<DateTime>(type: "datetime2", nullable: true),
                    NURSEVISIT = table.Column<DateTime>(type: "datetime2", nullable: true),
                    EPIPEN = table.Column<bool>(type: "bit", nullable: false),
                    INHALER = table.Column<bool>(type: "bit", nullable: false),
                    BENADRYL = table.Column<bool>(type: "bit", nullable: false),
                    HCPREV = table.Column<DateTime>(type: "datetime2", nullable: true),
                    NURSEVISI2 = table.Column<DateTime>(type: "datetime2", nullable: true),
                    SFAX = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ADDLOC2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ADDLOC3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ADDLOC4 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NURSEVISI3 = table.Column<DateTime>(type: "datetime2", nullable: true),
                    SCOPEFAX = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ASCAP1 = table.Column<int>(type: "int", nullable: true),
                    ASCAP2 = table.Column<int>(type: "int", nullable: true),
                    ASCAP3 = table.Column<int>(type: "int", nullable: true),
                    ASCAP4 = table.Column<int>(type: "int", nullable: true),
                    PEMAIL = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PK = table.Column<bool>(type: "bit", nullable: false),
                    UPK = table.Column<bool>(type: "bit", nullable: false),
                    EADR21 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    EADR22 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    EADR23 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    EPHONE2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    AMBPHONE = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ADDEMGINFO = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ROOM_NO2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ROOM_NO3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ROOM_NO4 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CAP1 = table.Column<int>(type: "int", nullable: true),
                    CAP2 = table.Column<int>(type: "int", nullable: true),
                    CAP3 = table.Column<int>(type: "int", nullable: true),
                    CAP4 = table.Column<int>(type: "int", nullable: true),
                    OSSPLACE = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ScopeEmail = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ScopePassword = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    MidPoint = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    StaffingAssistantName = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    StaffingAssistantPhone = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    StaffingAssistantFax = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    StaffingAssistantEmail = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    StaffingAssistantOthers = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    StaffingAssistantExt = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    StaffingAssistantForms = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FoodContactName = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FoodContactPhone = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FoodContactFax = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FoodContactEmail = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FoodContactOthers = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FoodContactExt = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FoodContactForms = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SupplyContactName = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SupplyContactPhone = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SupplyContactFax = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SupplyContactEmail = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SupplyContactOthers = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SupplyContactExt = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SupplyContactForms = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PettyCashSpecialEventContactName = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PettyCashSpecialEventContactPhone = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PettyCashSpecialEventContactFax = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PettyCashSpecialEventContactEmail = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PettyCashSpecialEventContactOthers = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PettyCashSpecialEventContactExt = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PettyCashSpecialEventContactForms = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FieldSupervisorName = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FieldSupervisorPhone = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FieldSupervisorFax = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FieldSupervisorEmail = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FieldSupervisorOthers = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FieldSupervisorExt = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FieldSupervisorForms = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FieldTrainerName = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FieldTrainerPhone = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FieldTrainerFax = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FieldTrainerEmail = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FieldTrainerOthers = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FieldTrainerExt = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FieldTrainerForms = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    HealthCareConsultantName = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    HealthCareConsultantPhone = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    HealthCareConsultantFax = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    HealthCareConsultantEmail = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    HealthCareConsultantOthers = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    HealthCareConsultantExt = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    HealthCareConsultantForms = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    RegistarName = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    RegistarPhone = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    RegistarFax = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    RegistarEmail = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    RegistarOthers = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    RegistarExt = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    RegistarForms = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    AccountBillingName = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    AccountBillingPhone = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    AccountBillingFax = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    AccountBillingEmail = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    AccountBillingOthers = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    AccountBillingExt = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    AccountBillingForms = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubstitutesName = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubstitutesPhone = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubstitutesFax = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubstitutesEmail = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubstitutesOthers = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubstitutesExt = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubstitutesForms = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SuppliesName = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SuppliesPhone = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SuppliesFax = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SuppliesEmail = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SuppliesOthers = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SuppliesExt = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SuppliesForms = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    AccountAssistantOthers = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Type = table.Column<long>(type: "bigint", nullable: true),
                    Priority = table.Column<long>(type: "bigint", nullable: true),
                    SCOPEDSSName = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SCOPEDSSPhone = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SCOPEDSSFax = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SCOPEDSSEmail = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SCOPEDSSOthers = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SCOPEDSSExt = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SCOPEDSSForms = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PresentersName = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PresentersPhone = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PresentersFax = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PresentersEmail = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PresentersOthers = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PresentersExt = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PresentersForms = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    AccountAssistantName = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    AccountAssistantPhone = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    AccountAssistantFax = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    AccountAssistantEmail = table.Column<string>(type: "nvarchar(max)", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Sites", x => x.SiteID);
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Sites");
        }
    }
}
