// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240923053232_Absences_table_site")]
    partial class Absences_table_site
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Entities.Absence", b =>
                {
                    b.Property<long>("AbsentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AbsentID"));

                    b.Property<string>("AbsentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Id")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("AbsentID");

                    b.ToTable("Absences");
                });

            modelBuilder.Entity("Core.Entities.AbsenceReasons", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("AbsenceReasons");
                });

            modelBuilder.Entity("Core.Entities.Attendance", b =>
                {
                    b.Property<long>("AttendanceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AttendanceID"));

                    b.Property<bool?>("CHARGED")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("FRACTION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("PAID")
                        .HasColumnType("bit");

                    b.Property<string>("REASON")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ReasonID")
                        .HasColumnType("bigint");

                    b.Property<string>("SITENAM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("SITENUM")
                        .HasColumnType("bigint");

                    b.Property<long?>("STAFF_ID")
                        .HasColumnType("bigint");

                    b.HasKey("AttendanceID");

                    b.ToTable("Attendance");
                });

            modelBuilder.Entity("Core.Entities.Closing", b =>
                {
                    b.Property<long>("ClosingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ClosingID"));

                    b.Property<DateTime?>("DATE")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DistrictID")
                        .HasColumnType("bigint");

                    b.Property<bool>("MakeUpDay")
                        .HasColumnType("bit");

                    b.Property<string>("NOTES")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PARENT_CR")
                        .HasColumnType("bit");

                    b.Property<bool>("STAFF_ALL")
                        .HasColumnType("bit");

                    b.Property<bool>("STAFF_DT")
                        .HasColumnType("bit");

                    b.Property<bool>("STAFF_PH")
                        .HasColumnType("bit");

                    b.Property<long?>("STATUS")
                        .HasColumnType("bigint");

                    b.HasKey("ClosingID");

                    b.ToTable("Closings");
                });

            modelBuilder.Entity("Core.Entities.Contact", b =>
                {
                    b.Property<long>("ContactID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ContactID"));

                    b.Property<string>("CHILD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONTACT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SITUATION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("SiteID")
                        .HasColumnType("bigint");

                    b.HasKey("ContactID");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("Core.Entities.District", b =>
                {
                    b.Property<long>("DistrictID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DistrictID"));

                    b.Property<bool?>("ACTIVE")
                        .HasColumnType("bit");

                    b.Property<string>("ADDR1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADDR12")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADDR2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADDR22")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADDR3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADDR32")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BHEMERCON")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BHEMERFON")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BUILDING")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CITY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CLASS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("CONTRACT")
                        .HasColumnType("bit");

                    b.Property<string>("COUNTY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DIST_NAM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("DIST_NUM")
                        .HasColumnType("bigint");

                    b.Property<string>("EMAIL1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMAIL2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMAILSUPER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FAX")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KINFON")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KINPER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("KINREG")
                        .HasColumnType("datetime2");

                    b.Property<string>("KNDRGRTN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LEMAIL1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LEMAIL2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LFAX")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LIAISON")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LIASON2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LPAX2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LPHONE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LPHONE2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NOTES")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PHONE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RSPNSBL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SECRETARY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SECRETARY2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STATE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STREET")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SUPER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SUPERVISOR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TERMS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TITLE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TITLE2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TRAINER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZIP")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DistrictID");

                    b.ToTable("Districts", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Inservice", b =>
                {
                    b.Property<long>("InserviceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("InserviceID"));

                    b.Property<DateTime?>("DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("Flag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("HOURS")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NOTES")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Paid")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SPONSOR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("STAFF_ID")
                        .HasColumnType("bigint");

                    b.Property<string>("TRAINING")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("TopicID")
                        .HasColumnType("bigint");

                    b.Property<long?>("WorkShopTypeID")
                        .HasColumnType("bigint");

                    b.HasKey("InserviceID");

                    b.ToTable("Inservices");
                });

            modelBuilder.Entity("Core.Entities.Personel", b =>
                {
                    b.Property<long>("PersonalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PersonalID"));

                    b.Property<string>("ABSENCES")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ACES")
                        .HasColumnType("datetime2");

                    b.Property<string>("AIDEFOR1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AIDEFOR2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AIDEFOR3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ALLOTTEDA")
                        .HasColumnType("int");

                    b.Property<int?>("ALLOTTEDB")
                        .HasColumnType("int");

                    b.Property<int?>("ALLOTTEDD")
                        .HasColumnType("int");

                    b.Property<bool?>("ALLUSED")
                        .HasColumnType("bit");

                    b.Property<bool?>("APP")
                        .HasColumnType("bit");

                    b.Property<bool?>("AloneWithChildren")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CBC")
                        .HasColumnType("datetime2");

                    b.Property<string>("CITY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CLEARMAIL")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CLEARREC")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CLR2BMAIL")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CNTY_FPC")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CNTY_FPR")
                        .HasColumnType("datetime2");

                    b.Property<string>("COMMENT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("COMMENTS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CPR")
                        .HasColumnType("datetime2");

                    b.Property<string>("DATESUSED")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DAYEMERG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DAYSOFF")
                        .HasColumnType("int");

                    b.Property<int?>("DAYSUSED")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DOEMP")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DOTERM")
                        .HasColumnType("datetime2");

                    b.Property<string>("DSS_POS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EDUCATION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ELaw")
                        .HasColumnType("datetime2");

                    b.Property<string>("EMAIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMERCELL1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMERCELL2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMERNAME1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMERNAME2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMERPHONE1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMERPHONE2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EffectiveDateAfter")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectiveDateBefore")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectiveDateDuring")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpungeDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FINGERCNTY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FIRSTAID")
                        .HasColumnType("datetime2");

                    b.Property<string>("FIRSTNAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FRI_1_B")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FRI_1_E")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FRI_2_B")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FRI_2_E")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FRI_3_B")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FRI_3_E")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FingerprintDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("FlagType")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Foundations")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Foundations15H")
                        .HasColumnType("datetime2");

                    b.Property<string>("GENDER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("HIRELETTER")
                        .HasColumnType("bit");

                    b.Property<string>("HOMEPHONE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("I9")
                        .HasColumnType("bit");

                    b.Property<bool?>("ID1")
                        .HasColumnType("bit");

                    b.Property<bool?>("ID2")
                        .HasColumnType("bit");

                    b.Property<bool?>("IDCA")
                        .HasColumnType("bit");

                    b.Property<decimal?>("JAN_PAY_RATE_A")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("JAN_PAY_RATE_B")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("JAN_PAY_RATE_D")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LASTNAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LeaveEndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LeaveOfAbsense")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LeaveStartDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Leaves")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LeavesEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LeavesStart")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("MATAPP")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("MATDATE")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("MAX_ADD_A")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MAX_ADD_B")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MAX_ADD_D")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MAX_HRS_A")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MAX_HRS_B")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MAX_HRS_D")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("MEDICALEXP")
                        .HasColumnType("datetime2");

                    b.Property<string>("MI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MON_1_B")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MON_1_E")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MON_2_B")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MON_2_E")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MON_3_B")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MON_3_E")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("MatStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("NYSID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OTHERPHONE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PAY_RATE_A")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PAY_RATE_B")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PAY_RATE_D")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PERC_A")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PERC_B")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PERC_D")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PersonalFieldSupervisor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonalFieldTrainer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonalHHC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RAISEEFFA")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RAISEEFFB")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RAISEEFFD")
                        .HasColumnType("datetime2");

                    b.Property<string>("REFEREDBY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("REF_P_FON")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("REF_P_OUT")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("REF_P_REC")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("REF_W1_FON")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("REF_W1_OUT")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("REF_W1_REC")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("REF_W2_FON")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("REF_W2_OUT")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("REF_W2_REC")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("REHIREABLE")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("REHIRED")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("SALARY_A")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SALARY_B")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SALARY_D")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("SEL")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("SEP_PAY_RATE_A")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SEP_PAY_RATE_B")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SEP_PAY_RATE_D")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("SHarassmentExp")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SHarassmentExp2")
                        .HasColumnType("datetime2");

                    b.Property<string>("SITE_NAM_A")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SITE_NAM_B")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SITE_NAM_D")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("SITE_NUM_A")
                        .HasColumnType("bigint");

                    b.Property<long?>("SITE_NUM_B")
                        .HasColumnType("bigint");

                    b.Property<long?>("SITE_NUM_D")
                        .HasColumnType("bigint");

                    b.Property<string>("SITE_POS_A")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SITE_POS_B")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SITE_POS_D")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SSN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("STAFF_ID")
                        .HasColumnType("bigint");

                    b.Property<string>("STATE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("STATE_FPC")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("STATE_FPR")
                        .HasColumnType("datetime2");

                    b.Property<string>("STREET")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Suspension")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SuspensionEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SuspensionEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SuspensionStart")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SuspensionStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("THU_1_B")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("THU_1_E")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("THU_2_B")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("THU_2_E")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("THU_3_B")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("THU_3_E")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TINEEXP")
                        .HasColumnType("datetime2");

                    b.Property<string>("TUE_1_B")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TUE_1_E")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TUE_2_B")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TUE_2_E")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TUE_3_B")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TUE_3_E")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Type")
                        .HasColumnType("int");

                    b.Property<bool?>("W4")
                        .HasColumnType("bit");

                    b.Property<string>("WED_1_B")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WED_1_E")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WED_2_B")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WED_2_E")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WED_3_B")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WED_3_E")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WORKPHONE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("WPREC")
                        .HasColumnType("bit");

                    b.Property<bool?>("WPREQ")
                        .HasColumnType("bit");

                    b.Property<string>("ZIPCODE")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonalID");

                    b.ToTable("Personel", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Positions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PositionId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Positions", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Report", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Reports", (string)null);
                });

            modelBuilder.Entity("Core.Entities.SchedularTimesheet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<TimeSpan?>("AdditionalStart")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("AdditionalStop")
                        .HasColumnType("time");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("LunchIn")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("LunchOut")
                        .HasColumnType("time");

                    b.Property<long?>("PersonID")
                        .HasColumnType("bigint");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ScheduleId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SiteID")
                        .HasColumnType("bigint");

                    b.Property<string>("SiteType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("TimeIn")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("TimeOut")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("PersonID");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("SiteID");

                    b.ToTable("SchedularTimesheets");
                });

            modelBuilder.Entity("Core.Entities.Schedule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<TimeSpan?>("AdditionalStart")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("AdditionalStop")
                        .HasColumnType("time");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("LunchIn")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("LunchOut")
                        .HasColumnType("time");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PersonID")
                        .HasColumnType("bigint");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("SiteID")
                        .HasColumnType("bigint");

                    b.Property<string>("SiteType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("TimeIn")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("TimeOut")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("PersonID");

                    b.HasIndex("SiteID");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("Core.Entities.School", b =>
                {
                    b.Property<long>("SchoolID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SchoolID"));

                    b.Property<string>("ADDR1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADDR2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DISMISAL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DIST_NAM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DIST_NUM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMAIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Hidden")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PRINCIPAL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SCH_NAM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SCH_NUM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SITE_NAM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SITE_NUM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TRANS")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SchoolID");

                    b.ToTable("Schools", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Site", b =>
                {
                    b.Property<long>("SiteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SiteID"));

                    b.Property<string>("ADDEMGINFO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADDLOC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADDLOC2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADDLOC3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADDLOC4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADDR1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADDR2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADDR3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AMBPHONE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("AMPM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ASCAP1")
                        .HasColumnType("int");

                    b.Property<int?>("ASCAP2")
                        .HasColumnType("int");

                    b.Property<int?>("ASCAP3")
                        .HasColumnType("int");

                    b.Property<int?>("ASCAP4")
                        .HasColumnType("int");

                    b.Property<string>("ATTNOTE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AUTORENEW")
                        .HasColumnType("bit");

                    b.Property<string>("AccountAssistantEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountAssistantFax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountAssistantName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountAssistantOthers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountAssistantPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountBillingEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountBillingExt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountBillingFax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountBillingForms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountBillingName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountBillingOthers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountBillingPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("BENADRYL")
                        .HasColumnType("bit");

                    b.Property<int?>("CAP1")
                        .HasColumnType("int");

                    b.Property<int?>("CAP2")
                        .HasColumnType("int");

                    b.Property<int?>("CAP3")
                        .HasColumnType("int");

                    b.Property<int?>("CAP4")
                        .HasColumnType("int");

                    b.Property<int?>("CAPACTIY")
                        .HasColumnType("int");

                    b.Property<string>("CLASS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CLOSED")
                        .HasColumnType("datetime2");

                    b.Property<string>("CLOSINGS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("COEXP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("COUNTY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DAILY")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DIST_FEE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DSS_FON")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DSS_REP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DT_VOL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EADR1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EADR2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EADR21")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EADR22")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EADR23")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EADR3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMERGENCY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ENROLLMENT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("EPHONE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EPHONE2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EPIPEN")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("EXPIRES")
                        .HasColumnType("datetime2");

                    b.Property<string>("FADR1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FADR2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FADR3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FPHONE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("FULL")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FieldSupervisorEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldSupervisorExt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldSupervisorFax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldSupervisorForms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldSupervisorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldSupervisorOthers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldSupervisorPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldTrainerEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldTrainerExt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldTrainerFax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldTrainerForms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldTrainerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldTrainerOthers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldTrainerPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoodContactEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoodContactExt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoodContactFax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoodContactForms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoodContactName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoodContactOthers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoodContactPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GRADE_LVLS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("HCPAPPR")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("HCPREV")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("HCPSENT")
                        .HasColumnType("datetime2");

                    b.Property<string>("HealthCareConsultantEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HealthCareConsultantExt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HealthCareConsultantFax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HealthCareConsultantForms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HealthCareConsultantName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HealthCareConsultantOthers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HealthCareConsultantPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("INHALER")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ISSUED")
                        .HasColumnType("datetime2");

                    b.Property<string>("LNDLNLOC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LOCKDOWN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MIN")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MidPoint")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NOTES")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NURSEVISI2")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NURSEVISI3")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NURSEVISIT")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ORIGCONTRC")
                        .HasColumnType("datetime2");

                    b.Property<string>("OSSPLACE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PADR1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PADR2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PADR3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PC_AMT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PC_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("PEMAIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PERMIT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PHONE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PHONE_TYPE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PK")
                        .HasColumnType("bit");

                    b.Property<string>("PPHONE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PRINCIPAL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PettyCashSpecialEventContactEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PettyCashSpecialEventContactExt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PettyCashSpecialEventContactFax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PettyCashSpecialEventContactForms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PettyCashSpecialEventContactName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PettyCashSpecialEventContactOthers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PettyCashSpecialEventContactPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PresentersEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PresentersExt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PresentersFax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PresentersForms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PresentersName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PresentersOthers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PresentersPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Priority")
                        .HasColumnType("bigint");

                    b.Property<string>("RELOCROOM1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RELOCROOM2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ROOM_NO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ROOM_NO2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ROOM_NO3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ROOM_NO4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RSPNSBL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistarEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistarExt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistarFax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistarForms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistarName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistarOthers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistarPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SAFEPLACE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SCHFONE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SCOPEDSSEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SCOPEDSSExt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SCOPEDSSFax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SCOPEDSSForms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SCOPEDSSName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SCOPEDSSOthers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SCOPEDSSPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SCOPEFAX")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SECPHONE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SECURITY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SFAX")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SITECAP")
                        .HasColumnType("int");

                    b.Property<string>("SITE_NAM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SITE_NUM")
                        .HasColumnType("bigint");

                    b.Property<string>("SRCSCHLS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("STARTED")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("START_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("START_TIME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STOP_TIME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScopeEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScopePassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffingAssistantEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffingAssistantExt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffingAssistantFax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffingAssistantForms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffingAssistantName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffingAssistantOthers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffingAssistantPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubstitutesEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubstitutesExt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubstitutesFax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubstitutesForms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubstitutesName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubstitutesOthers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubstitutesPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuppliesEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuppliesExt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuppliesFax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuppliesForms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuppliesName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuppliesOthers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuppliesPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplyContactEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplyContactExt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplyContactFax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplyContactForms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplyContactName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplyContactOthers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplyContactPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TEL_VOL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TIME_AVAIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TPPHONE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TRANSPORT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TWONAMES")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Type")
                        .HasColumnType("bigint");

                    b.Property<bool>("UPK")
                        .HasColumnType("bit");

                    b.Property<decimal?>("VISIT_ID")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("WAIVEREXP")
                        .HasColumnType("datetime2");

                    b.Property<string>("WHEN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("WL_COUNT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("WL_DATE")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SiteID");

                    b.ToTable("Sites", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Status", b =>
                {
                    b.Property<long>("StatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("StatusID"));

                    b.Property<bool>("Hidden")
                        .HasColumnType("bit");

                    b.Property<string>("StatusName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StatusID");

                    b.ToTable("Status");
                });

            modelBuilder.Entity("Core.Entities.Timesheet", b =>
                {
                    b.Property<long>("TimesheetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TimesheetID"));

                    b.Property<TimeSpan?>("AdditionalStart")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("AdditionalStop")
                        .HasColumnType("time");

                    b.Property<DateTime?>("ClockInLocal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ClockOutLocal")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("DistrictID")
                        .HasColumnType("bigint");

                    b.Property<TimeSpan?>("LunchIn")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("LunchOut")
                        .HasColumnType("time");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotesDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotesHeader")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PersonID")
                        .HasColumnType("bigint");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("SchoolID")
                        .HasColumnType("bigint");

                    b.Property<long?>("SiteID")
                        .HasColumnType("bigint");

                    b.Property<TimeSpan?>("TimeIn")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("TimeOut")
                        .HasColumnType("time");

                    b.Property<DateTime?>("TimeSheetDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Type")
                        .HasColumnType("int");

                    b.HasKey("TimesheetID");

                    b.ToTable("Timesheet");
                });

            modelBuilder.Entity("Core.Entities.TopicType", b =>
                {
                    b.Property<long>("TopicID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TopicID"));

                    b.Property<string>("TopicName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TopicID");

                    b.ToTable("TopicType");
                });

            modelBuilder.Entity("Core.Entities.Visit", b =>
                {
                    b.Property<long>("VisitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("VisitID"));

                    b.Property<DateTime?>("DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NOTES")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("OFFICAL")
                        .HasColumnType("bit");

                    b.Property<bool?>("OTHER")
                        .HasColumnType("bit");

                    b.Property<bool?>("PROBLEM")
                        .HasColumnType("bit");

                    b.Property<bool?>("QUALITY")
                        .HasColumnType("bit");

                    b.Property<bool?>("STAFFING")
                        .HasColumnType("bit");

                    b.Property<long?>("SiteID")
                        .HasColumnType("bigint");

                    b.Property<string>("TIMEIN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TIMEOUT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("TRAINING")
                        .HasColumnType("bit");

                    b.HasKey("VisitID");

                    b.ToTable("Visits");
                });

            modelBuilder.Entity("Core.Entities.Workshop", b =>
                {
                    b.Property<long>("WorkshopID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("WorkshopID"));

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Hours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("Paid")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sponsor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("TypeID")
                        .HasColumnType("bigint");

                    b.Property<string>("WorkshopName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WorkshopID");

                    b.ToTable("Workshops");
                });

            modelBuilder.Entity("Core.Entities.WorkshopMember", b =>
                {
                    b.Property<long>("WorkshopMemberID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("WorkshopMemberID"));

                    b.Property<long?>("PersonID")
                        .HasColumnType("bigint");

                    b.Property<long?>("WorkshopID")
                        .HasColumnType("bigint");

                    b.HasKey("WorkshopMemberID");

                    b.HasIndex("WorkshopID");

                    b.ToTable("WorkshopMembers");
                });

            modelBuilder.Entity("Core.Entities.WorkshopTopic", b =>
                {
                    b.Property<long>("WorkshopTopicID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("WorkshopTopicID"));

                    b.Property<long?>("TopicID")
                        .HasColumnType("bigint");

                    b.Property<long?>("WorkshopID")
                        .HasColumnType("bigint");

                    b.HasKey("WorkshopTopicID");

                    b.HasIndex("WorkshopID");

                    b.ToTable("WorkshopTopics");
                });

            modelBuilder.Entity("Core.Entities.WorkshopType", b =>
                {
                    b.Property<long>("WorkshopTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("WorkshopTypeID"));

                    b.Property<string>("WorkshopTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WorkshopTypeID");

                    b.ToTable("WorkshopType");
                });

            modelBuilder.Entity("Core.Entities.SchedularTimesheet", b =>
                {
                    b.HasOne("Core.Entities.Personel", "Personel")
                        .WithMany()
                        .HasForeignKey("PersonID");

                    b.HasOne("Core.Entities.Schedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId");

                    b.HasOne("Core.Entities.Site", "Site")
                        .WithMany()
                        .HasForeignKey("SiteID");

                    b.Navigation("Personel");

                    b.Navigation("Schedule");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("Core.Entities.Schedule", b =>
                {
                    b.HasOne("Core.Entities.Personel", "Personel")
                        .WithMany()
                        .HasForeignKey("PersonID");

                    b.HasOne("Core.Entities.Site", "Site")
                        .WithMany()
                        .HasForeignKey("SiteID");

                    b.Navigation("Personel");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("Core.Entities.WorkshopMember", b =>
                {
                    b.HasOne("Core.Entities.Workshop", "Workshop")
                        .WithMany("WorkshopMembers")
                        .HasForeignKey("WorkshopID");

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("Core.Entities.WorkshopTopic", b =>
                {
                    b.HasOne("Core.Entities.Workshop", "Workshop")
                        .WithMany("WorkshopTopics")
                        .HasForeignKey("WorkshopID");

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("Core.Entities.Workshop", b =>
                {
                    b.Navigation("WorkshopMembers");

                    b.Navigation("WorkshopTopics");
                });
#pragma warning restore 612, 618
        }
    }
}
