// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240816065826_initial_migration")]
    partial class initial_migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Entities.District", b =>
                {
                    b.Property<long>("DistrictID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DistrictID"));

                    b.Property<bool?>("ACTIVE")
                        .HasColumnType("bit");

                    b.Property<string>("ADDR1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADDR12")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADDR2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADDR22")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADDR3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADDR32")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BHEMERCON")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BHEMERFON")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BUILDING")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CITY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CLASS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("CONTRACT")
                        .HasColumnType("bit");

                    b.Property<string>("COUNTY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DIST_NAM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("DIST_NUM")
                        .HasColumnType("bigint");

                    b.Property<string>("EMAIL1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMAIL2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMAILSUPER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FAX")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KINFON")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KINPER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("KINREG")
                        .HasColumnType("datetime2");

                    b.Property<string>("KNDRGRTN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LEMAIL1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LEMAIL2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LFAX")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LIAISON")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LIASON2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LPAX2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LPHONE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LPHONE2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NOTES")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PHONE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RSPNSBL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SECRETARY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SECRETARY2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STATE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STREET")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SUPER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SUPERVISOR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TERMS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TITLE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TITLE2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TRAINER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZIP")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DistrictID");

                    b.ToTable("Districts", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
