// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240821042221_district_country_nullable")]
    partial class district_country_nullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Entities.District", b =>
                {
                    b.Property<long>("DistrictID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DistrictID"));

                    b.Property<bool?>("ACTIVE")
                        .HasColumnType("bit");

                    b.Property<string>("ADDR1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADDR12")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADDR2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADDR22")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADDR3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADDR32")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BHEMERCON")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BHEMERFON")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BUILDING")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CITY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CLASS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("CONTRACT")
                        .HasColumnType("bit");

                    b.Property<string>("COUNTY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DIST_NAM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("DIST_NUM")
                        .HasColumnType("bigint");

                    b.Property<string>("EMAIL1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMAIL2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMAILSUPER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FAX")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KINFON")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KINPER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("KINREG")
                        .HasColumnType("datetime2");

                    b.Property<string>("KNDRGRTN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LEMAIL1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LEMAIL2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LFAX")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LIAISON")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LIASON2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LPAX2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LPHONE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LPHONE2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NOTES")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PHONE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RSPNSBL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SECRETARY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SECRETARY2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STATE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STREET")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SUPER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SUPERVISOR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TERMS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TITLE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TITLE2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TRAINER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZIP")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DistrictID");

                    b.ToTable("Districts", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Site", b =>
                {
                    b.Property<long>("SiteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SiteID"));

                    b.Property<string>("ADDEMGINFO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADDLOC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADDLOC2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADDLOC3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADDLOC4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADDR1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADDR2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADDR3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AMBPHONE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("AMPM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ASCAP1")
                        .HasColumnType("int");

                    b.Property<int?>("ASCAP2")
                        .HasColumnType("int");

                    b.Property<int?>("ASCAP3")
                        .HasColumnType("int");

                    b.Property<int?>("ASCAP4")
                        .HasColumnType("int");

                    b.Property<string>("ATTNOTE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AUTORENEW")
                        .HasColumnType("bit");

                    b.Property<string>("AccountAssistantEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountAssistantFax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountAssistantName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountAssistantOthers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountAssistantPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountBillingEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountBillingExt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountBillingFax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountBillingForms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountBillingName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountBillingOthers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountBillingPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("BENADRYL")
                        .HasColumnType("bit");

                    b.Property<int?>("CAP1")
                        .HasColumnType("int");

                    b.Property<int?>("CAP2")
                        .HasColumnType("int");

                    b.Property<int?>("CAP3")
                        .HasColumnType("int");

                    b.Property<int?>("CAP4")
                        .HasColumnType("int");

                    b.Property<int?>("CAPACTIY")
                        .HasColumnType("int");

                    b.Property<string>("CLASS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CLOSED")
                        .HasColumnType("datetime2");

                    b.Property<string>("CLOSINGS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("COEXP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("COUNTY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DAILY")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DIST_FEE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DSS_FON")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DSS_REP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DT_VOL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EADR1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EADR2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EADR21")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EADR22")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EADR23")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EADR3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMERGENCY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ENROLLMENT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("EPHONE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EPHONE2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EPIPEN")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("EXPIRES")
                        .HasColumnType("datetime2");

                    b.Property<string>("FADR1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FADR2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FADR3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FPHONE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("FULL")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FieldSupervisorEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldSupervisorExt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldSupervisorFax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldSupervisorForms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldSupervisorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldSupervisorOthers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldSupervisorPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldTrainerEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldTrainerExt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldTrainerFax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldTrainerForms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldTrainerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldTrainerOthers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldTrainerPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoodContactEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoodContactExt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoodContactFax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoodContactForms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoodContactName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoodContactOthers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoodContactPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GRADE_LVLS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("HCPAPPR")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("HCPREV")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("HCPSENT")
                        .HasColumnType("datetime2");

                    b.Property<string>("HealthCareConsultantEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HealthCareConsultantExt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HealthCareConsultantFax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HealthCareConsultantForms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HealthCareConsultantName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HealthCareConsultantOthers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HealthCareConsultantPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("INHALER")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ISSUED")
                        .HasColumnType("datetime2");

                    b.Property<string>("LNDLNLOC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LOCKDOWN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MIN")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MidPoint")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NOTES")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NURSEVISI2")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NURSEVISI3")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NURSEVISIT")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ORIGCONTRC")
                        .HasColumnType("datetime2");

                    b.Property<string>("OSSPLACE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PADR1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PADR2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PADR3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PC_AMT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PC_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("PEMAIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PERMIT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PHONE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PHONE_TYPE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PK")
                        .HasColumnType("bit");

                    b.Property<string>("PPHONE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PRINCIPAL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PettyCashSpecialEventContactEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PettyCashSpecialEventContactExt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PettyCashSpecialEventContactFax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PettyCashSpecialEventContactForms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PettyCashSpecialEventContactName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PettyCashSpecialEventContactOthers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PettyCashSpecialEventContactPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PresentersEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PresentersExt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PresentersFax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PresentersForms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PresentersName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PresentersOthers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PresentersPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Priority")
                        .HasColumnType("bigint");

                    b.Property<string>("RELOCROOM1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RELOCROOM2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ROOM_NO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ROOM_NO2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ROOM_NO3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ROOM_NO4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RSPNSBL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistarEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistarExt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistarFax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistarForms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistarName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistarOthers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistarPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SAFEPLACE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SCHFONE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SCOPEDSSEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SCOPEDSSExt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SCOPEDSSFax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SCOPEDSSForms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SCOPEDSSName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SCOPEDSSOthers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SCOPEDSSPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SCOPEFAX")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SECPHONE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SECURITY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SFAX")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SITECAP")
                        .HasColumnType("int");

                    b.Property<string>("SITE_NAM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SITE_NUM")
                        .HasColumnType("bigint");

                    b.Property<string>("SRCSCHLS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("STARTED")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("START_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("START_TIME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STOP_TIME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScopeEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScopePassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffingAssistantEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffingAssistantExt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffingAssistantFax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffingAssistantForms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffingAssistantName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffingAssistantOthers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffingAssistantPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubstitutesEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubstitutesExt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubstitutesFax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubstitutesForms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubstitutesName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubstitutesOthers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubstitutesPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuppliesEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuppliesExt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuppliesFax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuppliesForms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuppliesName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuppliesOthers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuppliesPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplyContactEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplyContactExt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplyContactFax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplyContactForms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplyContactName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplyContactOthers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplyContactPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TEL_VOL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TIME_AVAIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TPPHONE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TRANSPORT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TWONAMES")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Type")
                        .HasColumnType("bigint");

                    b.Property<bool>("UPK")
                        .HasColumnType("bit");

                    b.Property<decimal?>("VISIT_ID")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("WAIVEREXP")
                        .HasColumnType("datetime2");

                    b.Property<string>("WHEN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("WL_COUNT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("WL_DATE")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SiteID");

                    b.ToTable("Sites", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
