using System;
using System.ComponentModel.DataAnnotations;

namespace Core.Entities
{
    public class Site
    {
        [Key]
        public long SiteID { get; set; }
        public long SITE_NUM { get; set; }
        public string? SITE_NAM { get; set; }
        public string? WHEN { get; set; }
        public string? ADDR1 { get; set; }
        public string? ADDR2 { get; set; }
        public string? ADDR3 { get; set; }
        public string? GRADE_LVLS { get; set; }
        public string? PHONE { get; set; }
        public string? PHONE_TYPE { get; set; }
        public string? TIME_AVAIL { get; set; }
        public string? ROOM_NO { get; set; }
        public string? START_TIME { get; set; }
        public string? STOP_TIME { get; set; }
        public DateTime? START_DATE { get; set; }
        public decimal? FULL { get; set; }
        public decimal? MIN { get; set; }
        public decimal? DAILY { get; set; }
        public decimal? AMPM { get; set; }
        public string? PERMIT { get; set; }
        public DateTime? ISSUED { get; set; }
        public DateTime? STARTED { get; set; }
        public DateTime? CLOSED { get; set; }
        public DateTime? EXPIRES { get; set; }
        public string? NOTES { get; set; }
        public bool AUTORENEW { get; set; }
        public DateTime? ORIGCONTRC { get; set; }
        public string? DIST_FEE { get; set; }
        public string? DSS_REP { get; set; }
        public string? DSS_FON { get; set; }
        public int? CAPACTIY { get; set; }
        public int? SITECAP { get; set; }
        public string? CLASS { get; set; }
        public string? COUNTY { get; set; }
        public string? PRINCIPAL { get; set; }
        public string? SCHFONE { get; set; }
        public string? CLOSINGS { get; set; }
        public string? EMERGENCY { get; set; }
        public string? PADR1 { get; set; }
        public string? PADR2 { get; set; }
        public string? PADR3 { get; set; }
        public string? PPHONE { get; set; }
        public string? FADR1 { get; set; }
        public string? FADR2 { get; set; }
        public string? FADR3 { get; set; }
        public string? FPHONE { get; set; }
        public string? EADR1 { get; set; }
        public string? EADR2 { get; set; }
        public string? EADR3 { get; set; }
        public string? EPHONE { get; set; }
        public decimal? VISIT_ID { get; set; }
        public string? WL_DATE { get; set; }
        public decimal? WL_COUNT { get; set; }
        public DateTime? PC_DATE { get; set; }
        public decimal? PC_AMT { get; set; }
        public string? TRANSPORT { get; set; }
        public string? TPPHONE { get; set; }
        public string? TEL_VOL { get; set; }
        public string? DT_VOL { get; set; }
        public string? SECURITY { get; set; }
        public string? SECPHONE { get; set; }
        public string? SAFEPLACE { get; set; }
        public string? LOCKDOWN { get; set; }
        public string? RELOCROOM1 { get; set; }
        public string? RELOCROOM2 { get; set; }
        public string? LNDLNLOC { get; set; }
        public string? ADDLOC { get; set; }
        public string? ATTNOTE { get; set; }
        public string? SRCSCHLS { get; set; }
        public string? RSPNSBL { get; set; }
        public string? TWONAMES { get; set; }
        public DateTime? HCPSENT { get; set; }
        public DateTime? HCPAPPR { get; set; }
        public decimal? ENROLLMENT { get; set; }
        public string? COEXP { get; set; }
        public DateTime? WAIVEREXP { get; set; }
        public DateTime? NURSEVISIT { get; set; }
        public bool EPIPEN { get; set; }
        public bool INHALER { get; set; }
        public bool BENADRYL { get; set; }
        public DateTime? HCPREV { get; set; }
        public DateTime? NURSEVISI2 { get; set; }
        public string? SFAX { get; set; }
        public string? ADDLOC2 { get; set; }
        public string? ADDLOC3 { get; set; }
        public string? ADDLOC4 { get; set; }
        public DateTime? NURSEVISI3 { get; set; }
        public string? SCOPEFAX { get; set; }
        public int? ASCAP1 { get; set; }
        public int? ASCAP2 { get; set; }
        public int? ASCAP3 { get; set; }
        public int? ASCAP4 { get; set; }
        public string? PEMAIL { get; set; }
        public bool PK { get; set; }
        public bool UPK { get; set; }
        public string? EADR21 { get; set; }
        public string? EADR22 { get; set; }
        public string? EADR23 { get; set; }
        public string? EPHONE2 { get; set; }
        public string? AMBPHONE { get; set; }
        public string? ADDEMGINFO { get; set; }
        public string? ROOM_NO2 { get; set; }
        public string? ROOM_NO3 { get; set; }
        public string? ROOM_NO4 { get; set; }
        public int? CAP1 { get; set; }
        public int? CAP2 { get; set; }
        public int? CAP3 { get; set; }
        public int? CAP4 { get; set; }
        public string? OSSPLACE { get; set; }
        public string? ScopeEmail { get; set; }
        public string? ScopePassword { get; set; }
        public string? MidPoint { get; set; }
        public string? StaffingAssistantName { get; set; }
        public string? StaffingAssistantPhone { get; set; }
        public string? StaffingAssistantFax { get; set; }
        public string? StaffingAssistantEmail { get; set; }
        public string? StaffingAssistantOthers { get; set; }
        public string? StaffingAssistantExt { get; set; }
        public string? StaffingAssistantForms { get; set; }
        public string? FoodContactName { get; set; }
        public string? FoodContactPhone { get; set; }
        public string? FoodContactFax { get; set; }
        public string? FoodContactEmail { get; set; }
        public string? FoodContactOthers { get; set; }
        public string? FoodContactExt { get; set; }
        public string? FoodContactForms { get; set; }
        public string? SupplyContactName { get; set; }
        public string? SupplyContactPhone { get; set; }
        public string? SupplyContactFax { get; set; }
        public string? SupplyContactEmail { get; set; }
        public string? SupplyContactOthers { get; set; }
        public string? SupplyContactExt { get; set; }
        public string? SupplyContactForms { get; set; }
        public string? PettyCashSpecialEventContactName { get; set; }
        public string? PettyCashSpecialEventContactPhone { get; set; }
        public string? PettyCashSpecialEventContactFax { get; set; }
        public string? PettyCashSpecialEventContactEmail { get; set; }
        public string? PettyCashSpecialEventContactOthers { get; set; }
        public string? PettyCashSpecialEventContactExt { get; set; }
        public string? PettyCashSpecialEventContactForms { get; set; }
        public string? FieldSupervisorName { get; set; }
        public string? FieldSupervisorPhone { get; set; }
        public string? FieldSupervisorFax { get; set; }
        public string? FieldSupervisorEmail { get; set; }
        public string? FieldSupervisorOthers { get; set; }
        public string? FieldSupervisorExt { get; set; }
        public string? FieldSupervisorForms { get; set; }
        public string? FieldTrainerName { get; set; }
        public string? FieldTrainerPhone { get; set; }
        public string? FieldTrainerFax { get; set; }
        public string? FieldTrainerEmail { get; set; }
        public string? FieldTrainerOthers { get; set; }
        public string? FieldTrainerExt { get; set; }
        public string? FieldTrainerForms { get; set; }
        public string? HealthCareConsultantName { get; set; }
        public string? HealthCareConsultantPhone { get; set; }
        public string? HealthCareConsultantFax { get; set; }
        public string? HealthCareConsultantEmail { get; set; }
        public string? HealthCareConsultantOthers { get; set; }
        public string? HealthCareConsultantExt { get; set; }
        public string? HealthCareConsultantForms { get; set; }
        public string? RegistarName { get; set; }
        public string? RegistarPhone { get; set; }
        public string? RegistarFax { get; set; }
        public string? RegistarEmail { get; set; }
        public string? RegistarOthers { get; set; }
        public string? RegistarExt { get; set; }
        public string? RegistarForms { get; set; }
        public string? AccountBillingName { get; set; }
        public string? AccountBillingPhone { get; set; }
        public string? AccountBillingFax { get; set; }
        public string? AccountBillingEmail { get; set; }
        public string? AccountBillingOthers { get; set; }
        public string? AccountBillingExt { get; set; }
        public string? AccountBillingForms { get; set; }
        public string? SubstitutesName { get; set; }
        public string? SubstitutesPhone { get; set; }
        public string? SubstitutesFax { get; set; }
        public string? SubstitutesEmail { get; set; }
        public string? SubstitutesOthers { get; set; }
        public string? SubstitutesExt { get; set; }
        public string? SubstitutesForms { get; set; }
        public string? SuppliesName { get; set; }
        public string? SuppliesPhone { get; set; }
        public string? SuppliesFax { get; set; }
        public string? SuppliesEmail { get; set; }
        public string? SuppliesOthers { get; set; }
        public string? SuppliesExt { get; set; }
        public string? SuppliesForms { get; set; }
        public string? AccountAssistantOthers { get; set; }
        public long? Type { get; set; }
        public long? Priority { get; set; }
        public string? SCOPEDSSName { get; set; }
        public string? SCOPEDSSPhone { get; set; }
        public string? SCOPEDSSFax { get; set; }
        public string? SCOPEDSSEmail { get; set; }
        public string? SCOPEDSSOthers { get; set; }
        public string? SCOPEDSSExt { get; set; }
        public string? SCOPEDSSForms { get; set; }
        public string? PresentersName { get; set; }
        public string? PresentersPhone { get; set; }
        public string? PresentersFax { get; set; }
        public string? PresentersEmail { get; set; }
        public string? PresentersOthers { get; set; }
        public string? PresentersExt { get; set; }
        public string? PresentersForms { get; set; }
        public string? AccountAssistantName { get; set; }
        public string? AccountAssistantPhone { get; set; }
        public string? AccountAssistantFax { get; set; }
        public string? AccountAssistantEmail { get; set; }
        public double? Latitude { get; set; }
        public double? Longitude { get; set; }
    }
}
