using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Core.DTOs.Personel
{
    public class PersonelDto
    {
        public long PersonalID { get; set; }
        public long? STAFF_ID { get; set; }
        public string? SSN { get; set; }
        public string? LASTNAME { get; set; }
        public string? FIRSTNAME { get; set; }
        public string? MI { get; set; }
        public string? STREET { get; set; }
        public string? CITY { get; set; }
        public string? STATE { get; set; }
        public string? ZIPCODE { get; set; }
        public string? HOMEPHONE { get; set; }
        public string? WORKPHONE { get; set; }
        public string? OTHERPHONE { get; set; }
        public DateTime? DOEMP { get; set; }
        public DateTime? DOTERM { get; set; }
        public DateTime? DOB { get; set; }
        public bool? WPREQ { get; set; }
        public bool? WPREC { get; set; }
        public DateTime? CLR2BMAIL { get; set; }
        public DateTime? CLEARMAIL { get; set; }
        public DateTime? CLEARREC { get; set; }
        public bool? APP { get; set; }
        public bool? W4 { get; set; }
        public bool? I9 { get; set; }
        public DateTime? MEDICALEXP { get; set; }
        public DateTime? TINEEXP { get; set; }
        public DateTime? REF_P_OUT { get; set; }
        public DateTime? REF_P_REC { get; set; }
        public DateTime? REF_W1_OUT { get; set; }
        public DateTime? REF_W1_REC { get; set; }
        public DateTime? REF_W2_OUT { get; set; }
        public DateTime? REF_W2_REC { get; set; }
        public string? FINGERCNTY { get; set; }
        public long? SITE_NUM_B { get; set; }
        public string? SITE_NAM_B { get; set; }
        public string? SITE_POS_B { get; set; }
        public long? SITE_NUM_D { get; set; }
        public string? SITE_NAM_D { get; set; }
        public string? SITE_POS_D { get; set; }
        public long? SITE_NUM_A { get; set; }
        public string? SITE_NAM_A { get; set; }
        public string? SITE_POS_A { get; set; }
        public string? MON_1_B { get; set; }
        public string? MON_1_E { get; set; }
        public string? MON_2_B { get; set; }
        public string? MON_2_E { get; set; }
        public string? MON_3_B { get; set; }
        public string? MON_3_E { get; set; }
        public string? TUE_1_B { get; set; }
        public string? TUE_1_E { get; set; }
        public string? TUE_2_B { get; set; }
        public string? TUE_2_E { get; set; }
        public string? TUE_3_B { get; set; }
        public string? TUE_3_E { get; set; }
        public string? WED_1_B { get; set; }
        public string? WED_1_E { get; set; }
        public string? WED_2_B { get; set; }
        public string? WED_2_E { get; set; }
        public string? WED_3_B { get; set; }
        public string? WED_3_E { get; set; }
        public string? THU_1_B { get; set; }
        public string? THU_1_E { get; set; }
        public string? THU_2_B { get; set; }
        public string? THU_2_E { get; set; }
        public string? THU_3_B { get; set; }
        public string? THU_3_E { get; set; }
        public string? FRI_1_B { get; set; }
        public string? FRI_1_E { get; set; }
        public string? FRI_2_B { get; set; }
        public string? FRI_2_E { get; set; }
        public string? FRI_3_B { get; set; }
        public string? FRI_3_E { get; set; }
        public decimal? PAY_RATE_B { get; set; }
        public decimal? SEP_PAY_RATE_B { get; set; }
        public decimal? JAN_PAY_RATE_B { get; set; }
        public decimal? SALARY_B { get; set; }
        public decimal? MAX_HRS_B { get; set; }
        public decimal? PAY_RATE_D { get; set; }
        public decimal? SEP_PAY_RATE_D { get; set; }
        public decimal? JAN_PAY_RATE_D { get; set; }
        public decimal? SALARY_D { get; set; }
        public decimal? MAX_HRS_D { get; set; }
        public decimal? PAY_RATE_A { get; set; }
        public decimal? SEP_PAY_RATE_A { get; set; }
        public decimal? JAN_PAY_RATE_A { get; set; }
        public decimal? SALARY_A { get; set; }
        public decimal? MAX_HRS_A { get; set; }
        public string? COMMENTS { get; set; }
        public bool? IDCA { get; set; }
        public string? EDUCATION { get; set; }
        public int? DAYSOFF { get; set; }
        public bool? ALLUSED { get; set; }
        public string? DATESUSED { get; set; }
        public string? REFEREDBY { get; set; }
        public DateTime? STATE_FPC { get; set; }
        public DateTime? STATE_FPR { get; set; }
        public bool? HIRELETTER { get; set; }
        public DateTime? CNTY_FPC { get; set; }
        public DateTime? CNTY_FPR { get; set; }
        public DateTime? REF_P_FON { get; set; }
        public DateTime? REF_W1_FON { get; set; }
        public DateTime? REF_W2_FON { get; set; }
        public bool? ID1 { get; set; }
        public bool? ID2 { get; set; }
        public decimal? MAX_ADD_B { get; set; }
        public decimal? MAX_ADD_D { get; set; }
        public decimal? MAX_ADD_A { get; set; }
        public string? DSS_POS { get; set; }
        public string? ABSENCES { get; set; }
        public string? NYSID { get; set; }
        public string? GENDER { get; set; }
        public int? DAYSUSED { get; set; }
        public decimal? PERC_B { get; set; }
        public decimal? PERC_D { get; set; }
        public decimal? PERC_A { get; set; }
        public DateTime? MATAPP { get; set; }
        public DateTime? CPR { get; set; }
        public DateTime? FIRSTAID { get; set; }
        public DateTime? MATDATE { get; set; }
        public DateTime? RAISEEFFB { get; set; }
        public DateTime? RAISEEFFD { get; set; }
        public DateTime? RAISEEFFA { get; set; }
        public bool? REHIREABLE { get; set; }
        public string? COMMENT { get; set; }
        public string? EMAIL { get; set; }
        public string? EMERNAME1 { get; set; }
        public string? EMERPHONE1 { get; set; }
        public string? EMERCELL1 { get; set; }
        public string? EMERNAME2 { get; set; }
        public string? EMERPHONE2 { get; set; }
        public string? EMERCELL2 { get; set; }
        public string? DAYEMERG { get; set; }
        public DateTime? REHIRED { get; set; }
        public int? ALLOTTEDB { get; set; }
        public int? ALLOTTEDD { get; set; }
        public int? ALLOTTEDA { get; set; }
        public string? AIDEFOR1 { get; set; }
        public string? AIDEFOR2 { get; set; }
        public string? AIDEFOR3 { get; set; }
        public DateTime? MatStart { get; set; }
        public DateTime? SEL { get; set; }
        public string? PersonalFieldSupervisor { get; set; }
        public string? PersonalFieldTrainer { get; set; }
        public string? PersonalHHC { get; set; }
        public int? Type { get; set; }
        public DateTime? EffectiveDateBefore { get; set; }
        public DateTime? EffectiveDateDuring { get; set; }
        public DateTime? EffectiveDateAfter { get; set; }
        public DateTime? Foundations { get; set; }
        public bool LeaveOfAbsense { get; set; }
        public DateTime? LeaveStartDate { get; set; }
        public DateTime? LeaveEndDate { get; set; }
        public DateTime? SuspensionStartDate { get; set; }
        public DateTime? SuspensionEndDate { get; set; }
        public bool? Leaves { get; set; }
        public DateTime? LeavesStart { get; set; }
        public DateTime? LeavesEnd { get; set; }
        public bool? Suspension { get; set; }
        public DateTime? SuspensionStart { get; set; }
        public DateTime? SuspensionEnd { get; set; }
        public DateTime? ExpungeDate { get; set; }
        public bool? AloneWithChildren { get; set; }
        public bool? FlagType { get; set; }
        public DateTime? SHarassmentExp { get; set; }
        public DateTime? SHarassmentExp2 { get; set; }
        public DateTime? CBC { get; set; }
        public DateTime? ACES { get; set; }
        public DateTime? ELaw { get; set; }
        public DateTime? FingerprintDate { get; set; }
        public DateTime? Foundations15H { get; set; }
    }
}
